export const certificationsConstants = {
  title: "Formação e certificações",
  certificationsList: [
    {
      logoSrc: "./svg/experiences/senac.svg",
      logoAlt: "Logo do Senac",
      title: "Senac",
      width: 85,
      height: 50,
    },
    {
      logoSrc: "./svg/experiences/fiap.svg",
      logoAlt: "Logo da FIAP",
      title: "FIAP",
      width: 160,
      height: 50,
    },
    {
      logoSrc: "./svg/experiences/alura.svg",
      logoAlt: "Logo da Alura",
      title: "alura",
      width: 113,
      height: 64,
    },
    {
      logoSrc: "./svg/experiences/udemy.svg",
      logoAlt: "Logo da Udemy",
      title: "udemy",
      width: 127,
      height: 47,
    },
    {
      logoSrc: "./svg/experiences/etec-albert-einstein.svg",
      logoAlt: "Logo da ETEC Albert Einstein",
      title: "ETEC Albert Einstein",
      width: 100,
      height: 51,
    },
    {
      logoSrc: "./svg/experiences/ia-lab.svg",
      logoAlt: "Logo da IA Lab",
      title: "IA Lab",
      width: 124,
      height: 37,
    },
    {
      logoSrc: "./svg/experiences/code.svg",
      logoAlt: "Logo da CODE",
      title: "CODE",
      width: 51,
      height: 50,
    },
    {
      logoSrc: "./svg/experiences/grasshopper.svg",
      logoAlt: "Logo da Grasshopper",
      title: "Grasshopper",
      width: 148,
      height: 32,
    },
    {
      logoSrc: "./svg/experiences/senai.svg",
      logoAlt: "Logo do SENAI",
      title: "SENAI",
      width: 128,
      height: 35,
    },
    {
      logoSrc: "./svg/experiences/cps.svg",
      logoAlt: "Logo do Centro Paula Souza",
      title: "Centro Paula Souza",
      width: 124,
      height: 48,
    },
  ],
};
