import { GalleryProps } from "../props";

export const redesSociais: GalleryProps = {
  slug: "redes-sociais",
  title: "Redes Sociais",
  subtitle: "Conteúdo visual para marcas e campanhas digitais.",
  tags: ["Social Media", "Conteúdo", "Campanhas", "Branding", "Digital"],
  images: {
    specialHeight: true,
    imgs: [
      {
        src: "/imgs/galleries/redes-sociais/1.webp",
        alt: "Post de estilos para redes sociais",
        type: "2x2",
        width: 1080,
        height: 1920,
      },
      {
        src: "/imgs/galleries/redes-sociais/2.webp",
        alt: "Post O Diabo Veste Prada para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/3.webp",
        alt: "Post Swarovski para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/4.webp",
        alt: "Post Instax para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/5.webp",
        alt: "Post Cinemark para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/6.webp",
        alt: "Post Invasao Alien para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/7.webp",
        alt: "Post Janeiro Branco para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/10.webp",
        alt: "Post Capitao America para redes sociais",
        type: "2x2",
        width: 1080,
        height: 1920,
      },
      {
        src: "/imgs/galleries/redes-sociais/8.webp",
        alt: "Post Cinema para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/9.webp",
        alt: "Post Tartarugas Ninja para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/11.webp",
        alt: "Post Xdome para redes sociais",
        type: "2x2",
        width: 1080,
        height: 1920,
      },
      {
        src: "/imgs/galleries/redes-sociais/12.webp",
        alt: "Post Brazil Core para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/13.webp",
        alt: "Post culinaria peruana para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/14.webp",
        alt: "Post campanha de Dia das Maes para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/15.webp",
        alt: "Post O Boticario para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/16.webp",
        alt: "Post app Catuaí para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/17.webp",
        alt: "Post botoes redondos para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/20.webp",
        alt: "Post Arena Globo para redes sociais",
        type: "2x2",
        width: 1080,
        height: 1920,
      },
      {
        src: "/imgs/galleries/redes-sociais/18.webp",
        alt: "Post Renner para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
      {
        src: "/imgs/galleries/redes-sociais/19.webp",
        alt: "Post Empodera Ela para redes sociais",
        type: "1x1",
        width: 1080,
        height: 1350,
      },
    ],
  },
};
