export const experiencesConstants = {
  title: "Experiência com grandes marcas",
  experiencesList: [
    {
      src: "./svg/experiences/cea.svg",
      alt: "Logo da C&A",
      title: "C&A",
      width: 80,
      height: 59,
    },
    {
      src: "./svg/experiences/tambore.svg",
      alt: "Logo do Shopping Tamboré",
      title: "Shopping Tamboré",
      width: 136,
      height: 43,
    },
    {
      src: "./svg/experiences/vila-lobos.svg",
      alt: "Logo do Shopping Villa Lobos",
      title: "Shopping Villa Lobos",
      width: 143,
      height: 23,
    },
    {
      src: "./svg/experiences/norte-shopping.svg",
      alt: "Logo do Norte Shopping",
      title: "Norte Shopping",
      width: 141,
      height: 35,
    },
    {
      src: "./svg/experiences/catuai.svg",
      alt: "Logo do Catuaí Shopping",
      title: "Catuaí Shopping",
      width: 166,
      height: 55,
    },
    {
      src: "./svg/experiences/vila-velha.svg",
      alt: "Logo do Shopping Vila Velha",
      title: "Shopping Vila Velha",
      width: 163,
      height: 41,
    },
    {
      src: "./svg/experiences/lightland.svg",
      alt: "Logo da Lightland",
      title: "Lightland",
      width: 127,
      height: 60,
    },
    {
      src: "./svg/experiences/taste-lab.svg",
      alt: "Logo da Taste Lab",
      title: "Taste Lab",
      width: 136,
      height: 49,
    },
    {
      src: "./svg/experiences/jardim-sul.svg",
      alt: "Logo do Shopping Jardim Sul",
      title: "Shopping Jardim Sul",
      width: 135,
      height: 24,
    },
    {
      src: "./svg/experiences/sao-bernardo-plaza.svg",
      alt: "Logo do São Bernardo Plaza",
      title: "São Bernardo Plaza",
      width: 137,
      height: 63,
    },
    {
      src: "./svg/experiences/independencia.svg",
      alt: "Logo do Independência Shopping",
      title: "Independência Shopping",
      width: 100,
      height: 71,
    },
    {
      src: "./svg/experiences/cantareira.svg",
      alt: "Logo do Cantareira Norte Shopping",
      title: "Cantareira Norte Shopping",
      width: 113,
      height: 61,
    },
  ],
};
