import { BrandingCardProps } from "@/components/branding-card/props";

export const brands = {
  "C&A": {
    logoSrc: "/svg/experiences/cea.svg",
    logoAlt: "Logo da C&A",
    title: "C&A",
    width: 80,
    height: 59,
  },
  "Shopping Tamboré": {
    logoSrc: "/svg/experiences/tambore.svg",
    logoAlt: "Logo do Shopping Tamboré",
    title: "Shopping Tamboré",
    width: 136,
    height: 43,
  },
  "Shopping Villa Lobos": {
    logoSrc: "/svg/experiences/vila-lobos.svg",
    logoAlt: "Logo do Shopping Villa Lobos",
    title: "Shopping Villa Lobos",
    width: 143,
    height: 23,
  },
  "Norte Shopping": {
    logoSrc: "/svg/experiences/norte-shopping.svg",
    logoAlt: "Logo do Norte Shopping",
    title: "Norte Shopping",
    width: 141,
    height: 35,
  },
  "Catuaí Shopping": {
    logoSrc: "/svg/experiences/catuai.svg",
    logoAlt: "Logo do Catuaí Shopping",
    title: "Catuaí Shopping",
    width: 166,
    height: 55,
  },
  "Shopping Vila Velha": {
    logoSrc: "/svg/experiences/vila-velha.svg",
    logoAlt: "Logo do Shopping Vila Velha",
    title: "Shopping Vila Velha",
    width: 163,
    height: 41,
  },
  Lightland: {
    logoSrc: "/svg/experiences/lightland.svg",
    logoAlt: "Logo da Lightland",
    title: "Lightland",
    width: 127,
    height: 60,
  },
  "Taste Lab": {
    logoSrc: "/svg/experiences/taste-lab.svg",
    logoAlt: "Logo da Taste Lab",
    title: "Taste Lab",
    width: 136,
    height: 49,
  },
  "Shopping Jardim Sul": {
    logoSrc: "/svg/experiences/jardim-sul.svg",
    logoAlt: "Logo do Shopping Jardim Sul",
    title: "Shopping Jardim Sul",
    width: 135,
    height: 24,
  },
  "São Bernardo Plaza": {
    logoSrc: "/svg/experiences/sao-bernardo-plaza.svg",
    logoAlt: "Logo do São Bernardo Plaza",
    title: "São Bernardo Plaza",
    width: 137,
    height: 63,
  },
  "Independência Shopping": {
    logoSrc: "/svg/experiences/independencia.svg",
    logoAlt: "Logo do Independência Shopping",
    title: "Independência Shopping",
    width: 100,
    height: 71,
  },
  "Cantareira Norte Shopping": {
    logoSrc: "/svg/experiences/cantareira.svg",
    logoAlt: "Logo do Cantareira Norte Shopping",
    title: "Cantareira Norte Shopping",
    width: 113,
    height: 61,
  },
  Microsoft: {
    logoSrc: "/svg/experiences/microsoft.svg",
    logoAlt: "Logo da Microsoft",
    title: "Microsoft",
    width: 160,
    height: 80,
  },
  Azure: {
    logoSrc: "/svg/experiences/azure.svg",
    logoAlt: "Logo da Azure",
    title: "Azure",
    width: 100,
    height: 29,
  },
  AWS: {
    logoSrc: "/svg/experiences/aws.svg",
    logoAlt: "Logo da AWS",
    title: "AWS",
    width: 71,
    height: 48,
  },
  UNESCO: {
    logoSrc: "/svg/experiences/unesco.svg",
    logoAlt: "Logo da Unesco",
    title: "Unesco",
    width: 127,
    height: 28,
  },
  "UN Global Compact": {
    logoSrc: "/svg/experiences/un-global.svg",
    logoAlt: "Logo da UN Global Compact",
    title: "UN Global Compact",
    width: 64,
    height: 60,
  },
  "Kraft Heinz": {
    logoSrc: "/svg/experiences/kraftheinz.svg",
    logoAlt: "Logo da Kraft Heinz",
    title: "Kraft Heinz",
    width: 127,
    height: 22,
  },
  Hapvida: {
    logoSrc: "/svg/experiences/hapvida.svg",
    logoAlt: "Logo da Hapvida",
    title: "Hapvida",
    width: 148,
    height: 32,
  },
  Softtek: {
    logoSrc: "/svg/experiences/softtek.svg",
    logoAlt: "Logo da Softtek",
    title: "Softtek",
    width: 99,
    height: 50,
  },
  "CropLife Brasil": {
    logoSrc: "/svg/experiences/croplife.svg",
    logoAlt: "Logo da CropLife Brasil",
    title: "CropLife Brasil",
    width: 125,
    height: 45,
  },
  "Rede Oceano Limpo": {
    logoSrc: "/svg/experiences/rede-oceano.svg",
    logoAlt: "Logo da Rede Oceano Limpo",
    title: "Rede Oceano Limpo",
    width: 127,
    height: 40,
  },
  Senac: {
    logoSrc: "/svg/experiences/senac.svg",
    logoAlt: "Logo do Senac",
    title: "Senac",
    width: 85,
    height: 50,
  },
  FIAP: {
    logoSrc: "/svg/experiences/fiap.svg",
    logoAlt: "Logo da FIAP",
    title: "FIAP",
    width: 160,
    height: 50,
  },
  Alura: {
    logoSrc: "/svg/experiences/alura.svg",
    logoAlt: "Logo da Alura",
    title: "Alura",
    width: 113,
    height: 64,
  },
  Udemy: {
    logoSrc: "/svg/experiences/udemy.svg",
    logoAlt: "Logo da Udemy",
    title: "Udemy",
    width: 127,
    height: 47,
  },
  "ETEC Albert Einstein": {
    logoSrc: "/svg/experiences/etec-albert-einstein.svg",
    logoAlt: "Logo da ETEC Albert Einstein",
    title: "ETEC Albert Einstein",
    width: 100,
    height: 51,
  },
  "IA Lab": {
    logoSrc: "/svg/experiences/ia-lab.svg",
    logoAlt: "Logo da IA Lab",
    title: "IA Lab",
    width: 124,
    height: 37,
  },
  CODE: {
    logoSrc: "/svg/experiences/code.svg",
    logoAlt: "Logo da CODE",
    title: "CODE",
    width: 51,
    height: 50,
  },
  Grasshopper: {
    logoSrc: "/svg/experiences/grasshopper.svg",
    logoAlt: "Logo da Grasshopper",
    title: "Grasshopper",
    width: 148,
    height: 32,
  },
  SENAI: {
    logoSrc: "/svg/experiences/senai.svg",
    logoAlt: "Logo do SENAI",
    title: "SENAI",
    width: 128,
    height: 35,
  },
  "Centro Paula Souza": {
    logoSrc: "/svg/experiences/cps.svg",
    logoAlt: "Logo do Centro Paula Souza",
    title: "Centro Paula Souza",
    width: 124,
    height: 48,
  },
} satisfies Record<string, BrandingCardProps & { title: string }>;

export type BrandName = keyof typeof brands;
