import { BrandingCardProps } from "@/components/branding-card/props";

export const brands = {
  "C&A": {
    logoSrc: "/imgs/partners/cea.png",
    logoAlt: "Logo da C&A",
    title: "C&A",
    width: 81,
    height: 59,
  },
  "Shopping Tamboré": {
    logoSrc: "/imgs/partners/shopping-tambore.png",
    logoAlt: "Logo do Shopping Tamboré",
    title: "Shopping Tamboré",
    width: 136,
    height: 44,
  },
  "Shopping Villa Lobos": {
    logoSrc: "/imgs/partners/villa-lobos.png",
    logoAlt: "Logo do Shopping Villa Lobos",
    title: "Shopping Villa Lobos",
    width: 143,
    height: 23,
  },
  "Norte Shopping": {
    logoSrc: "/imgs/partners/norte-shopping.png",
    logoAlt: "Logo do Norte Shopping",
    title: "Norte Shopping",
    width: 141,
    height: 36,
  },
  "Catuaí Shopping": {
    logoSrc: "/imgs/partners/catuai.png",
    logoAlt: "Logo do Catuaí Shopping",
    title: "Catuaí Shopping",
    width: 166,
    height: 55,
  },
  "Shopping Vila Velha": {
    logoSrc: "/imgs/partners/shopping-vila-velha.png",
    logoAlt: "Logo do Shopping Vila Velha",
    title: "Shopping Vila Velha",
    width: 163,
    height: 41,
  },
  Lightland: {
    logoSrc: "/imgs/partners/lightland.png",
    logoAlt: "Logo da Lightland",
    title: "Lightland",
    width: 128,
    height: 60,
  },
  "Taste Lab": {
    logoSrc: "/imgs/partners/taste-lab.png",
    logoAlt: "Logo da Taste Lab",
    title: "Taste Lab",
    width: 136,
    height: 49,
  },
  "Shopping Jardim Sul": {
    logoSrc: "/imgs/partners/shopping-jardim-sul.png",
    logoAlt: "Logo do Shopping Jardim Sul",
    title: "Shopping Jardim Sul",
    width: 135,
    height: 25,
  },
  "São Bernardo Plaza": {
    logoSrc: "/imgs/partners/sao-bernardo-plaza-shopping.png",
    logoAlt: "Logo do São Bernardo Plaza",
    title: "São Bernardo Plaza",
    width: 137,
    height: 64,
  },
  "Independência Shopping": {
    logoSrc: "/imgs/partners/independencia-shopping.png",
    logoAlt: "Logo do Independência Shopping",
    title: "Independência Shopping",
    width: 100,
    height: 71,
  },
  "Cantareira Norte Shopping": {
    logoSrc: "/imgs/partners/cantareira-norte-shopping.png",
    logoAlt: "Logo do Cantareira Norte Shopping",
    title: "Cantareira Norte Shopping",
    width: 113,
    height: 61,
  },
  Microsoft: {
    logoSrc: "/imgs/partners/microsoft.png",
    logoAlt: "Logo da Microsoft",
    title: "Microsoft",
    width: 160,
    height: 80,
  },
  Azure: {
    logoSrc: "/imgs/partners/azure.png",
    logoAlt: "Logo da Azure",
    title: "Azure",
    width: 100,
    height: 29,
  },
  AWS: {
    logoSrc: "/imgs/partners/aws.png",
    logoAlt: "Logo da AWS",
    title: "AWS",
    width: 71,
    height: 47,
  },
  UNESCO: {
    logoSrc: "/imgs/partners/unesco.png",
    logoAlt: "Logo da Unesco",
    title: "Unesco",
    width: 127,
    height: 28,
  },
  "UN Global Compact": {
    logoSrc: "/imgs/partners/onu.png",
    logoAlt: "Logo da UN Global Compact",
    title: "UN Global Compact",
    width: 64,
    height: 60,
  },
  "Kraft Heinz": {
    logoSrc: "/imgs/partners/kraft-heinz.png",
    logoAlt: "Logo da Kraft Heinz",
    title: "Kraft Heinz",
    width: 127,
    height: 22,
  },
  Hapvida: {
    logoSrc: "/imgs/partners/hapvida.png",
    logoAlt: "Logo da Hapvida",
    title: "Hapvida",
    width: 148,
    height: 32,
  },
  Softtek: {
    logoSrc: "/imgs/partners/softtek.png",
    logoAlt: "Logo da Softtek",
    title: "Softtek",
    width: 99,
    height: 50,
  },
  "CropLife Brasil": {
    logoSrc: "/imgs/partners/croplife-brasil.png",
    logoAlt: "Logo da CropLife Brasil",
    title: "CropLife Brasil",
    width: 125,
    height: 45,
  },
  "Rede Oceano Limpo": {
    logoSrc: "/imgs/partners/rede-oceano-limpo.png",
    logoAlt: "Logo da Rede Oceano Limpo",
    title: "Rede Oceano Limpo",
    width: 127,
    height: 40,
  },
  Senac: {
    logoSrc: "/imgs/partners/senac.png",
    logoAlt: "Logo do Senac",
    title: "Senac",
    width: 85,
    height: 50,
  },
  FIAP: {
    logoSrc: "/imgs/partners/fiap.png",
    logoAlt: "Logo da FIAP",
    title: "FIAP",
    width: 160,
    height: 50,
  },
  Alura: {
    logoSrc: "/imgs/partners/alura.png",
    logoAlt: "Logo da Alura",
    title: "Alura",
    width: 113,
    height: 64,
  },
  Udemy: {
    logoSrc: "/imgs/partners/udemy.png",
    logoAlt: "Logo da Udemy",
    title: "Udemy",
    width: 127,
    height: 47,
  },
  "ETEC Albert Einstein": {
    logoSrc: "/imgs/partners/etec-albert-einstein.png",
    logoAlt: "Logo da ETEC Albert Einstein",
    title: "ETEC Albert Einstein",
    width: 100,
    height: 51,
  },
  "IA Lab": {
    logoSrc: "/imgs/partners/ia-lab.png",
    logoAlt: "Logo da IA Lab",
    title: "IA Lab",
    width: 124,
    height: 37,
  },
  CODE: {
    logoSrc: "/imgs/partners/code.png",
    logoAlt: "Logo da CODE",
    title: "CODE",
    width: 51,
    height: 50,
  },
  Grasshopper: {
    logoSrc: "/imgs/partners/grasshooper.png",
    logoAlt: "Logo da Grasshopper",
    title: "Grasshopper",
    width: 148,
    height: 32,
  },
  SENAI: {
    logoSrc: "/imgs/partners/senai.png",
    logoAlt: "Logo do SENAI",
    title: "SENAI",
    width: 128,
    height: 35,
  },
  "Centro Paula Souza": {
    logoSrc: "/imgs/partners/cps.png",
    logoAlt: "Logo do Centro Paula Souza",
    title: "Centro Paula Souza",
    width: 124,
    height: 48,
  },
} satisfies Record<string, BrandingCardProps & { title: string }>;

export type BrandName = keyof typeof brands;
