import type { Metadata } from "next";
import { Lato } from "next/font/google";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyles } from "@/styles/global";
import { AppThemeProvider } from "@/contexts/theme-provider";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Cibele Rodrigues",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lato.variable}`}>
      <body>
        <StyledComponentsRegistry>
          <AppThemeProvider>
            <GlobalStyles />
            {children}
          </AppThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
