import { GalleryProps } from "../props";

export const campanhas: GalleryProps = {
  slug: "campanhas",
  title: "Campanhas",
  subtitle: "Key visuals, banners e desdobramentos para canais on e off.",
  tags: ["Key Visual", "Mídia On", "Mídia Off", "Banners", "Desdobramentos"],
  images: {
    specialHeight: true,
    specialGrid: true,
    imgs: [
      {
        src: "/imgs/galleries/campanhas/1.webp",
        alt: "Campanha Beer and Beef",
        type: "2x2",
        width: 1080,
        height: 1920,
      },
      {
        src: "/imgs/galleries/campanhas/2.webp",
        alt: "Campanha Complan Norte Shopping",
        type: "3x1",
        width: 1772,
        height: 1181,
      },
      {
        src: "/imgs/galleries/campanhas/3.webp",
        alt: "Padrao visual de campanha",
        type: "3x1",
        width: 4933,
        height: 4905,
      },
      {
        src: "/imgs/galleries/campanhas/4.webp",
        alt: "Campanha Outback Chocolate Thunder",
        type: "3x1",
        width: 1920,
        height: 1080,
      },
      {
        src: "/imgs/galleries/campanhas/6.webp",
        alt: "Campanha sustentabilidade Catuaí",
        type: "2x2",
        width: 2469,
        height: 3508,
      },
      {
        src: "/imgs/galleries/campanhas/5.webp",
        alt: "Campanha Arraia Catuaí",
        type: "3x1",
        width: 1920,
        height: 1080,
      },

      {
        src: "/imgs/galleries/campanhas/7.webp",
        alt: "Campanha Cliente Estrela",
        type: "2x2",
        width: 1200,
        height: 1800,
      },
      {
        src: "/imgs/galleries/campanhas/8.webp",
        alt: "Campanha Save the Date",
        type: "3x1",
        width: 750,
        height: 422,
      },
      {
        src: "/imgs/galleries/campanhas/9.webp",
        alt: "Campanha Diversao Taste Lab",
        type: "3x1",
        width: 700,
        height: 400,
      },
      {
        src: "/imgs/galleries/campanhas/10.webp",
        alt: "Campanha Arena Globo",
        type: "3x1",
        width: 2500,
        height: 1668,
      },
      {
        src: "/imgs/galleries/campanhas/12.webp",
        alt: "Campanha Taste Lab Beatles Fever",
        type: "2x2",
        width: 1702,
        height: 2439,
      },
      {
        src: "/imgs/galleries/campanhas/11.webp",
        alt: "Campanha BistroGoro",
        type: "3x1",
        width: 750,
        height: 422,
      },
      {
        src: "/imgs/galleries/campanhas/13.webp",
        alt: "Campanha harmonizacao de vinhos",
        type: "2x2",
        width: 1956,
        height: 2920,
      },
      {
        src: "/imgs/galleries/campanhas/14.webp",
        alt: "Campanha Cliente Hospitalar",
        type: "3x1",
        width: 720,
        height: 400,
      },
      {
        src: "/imgs/galleries/campanhas/15.webp",
        alt: "Campanha pizzas em dobro",
        type: "3x1",
        width: 1921,
        height: 1081,
      },
    ],
  },
};
